jobs:
  check:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Download Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./check/main

name: Verify

on:
  schedule:
    - cron: "10 */6 * * *"
